### ISSUE TITLE
Make escaping optional

### ISSUE THREAD

**Issue by kjw1** [soranoba/bbmustache#10]
I think it would be useful to not do html escaping for non web page rendering purposes.

**Comment by soranoba** [comment]
https://mustache.github.io/mustache.5.html

> All variables are HTML escaped by default. If you want to return unescaped HTML, use the triple mustache: {{{name}}}.

Do you want this? Or, is not it enough with this?

**Comment by kjw1** [comment]
Didn't realize that was already supported, didn't see it in the docs. Thanks.

**Comment by subjectdenied** [comment]
when 3 geschwungene klammern anstatt 2 verwendet werden für die placeholder, wird das html-escaping der bbmustache-render-engine deaktiviert
