### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by dzimi** [soranoba/bbmustache#13]
Hi!

I've noticed that the newest version v1.1.0 is not backward compatible with the version v1.0.4 in the escaping context. 
v1.04:

    bbmustache:render(<<"{{{profile_dir}}}/bin/app1_402184">>, [{profile_dir, "/home/test/test"}], [{key_type, atom}]).
    <<"/home/test/test/bin/app1_402184">>

v1.1.0:

    bbmustache:render(<<"{{profile_dir}}/bin/app1_402184">>, [{profile_dir, "/home/test/test"}], [{key_type, atom}]).
    <<"&#x2F;home&#x2F;test&#x2F;test/bin/app1_402184">>

This example is taken from rebar3 common tests. I tried to upgrade bbmustache for rebar3, but due to this incompatibility I could not. Event, when I fixed the test, there is a problem with rebar3 itself. I think in many places it uses bbmustache:render function with "paths" as a  variables, which are escaped in v.1.1.0. 
It would be nice if new version would be backaward compatible or maybe as a workaround , the option `unescape` could be passed to the `render` function. It would be much easier only to add this parameter. What do you think about that?

**Comment by soranoba** [comment]
Hi, @dzimi 

I think that the backward compatibility is important.
If I change the interface of function, I will do a major update.

However, I think that [this case](https://github.com/soranoba/bbmustache/commit/596a67288b32401f39957a099733a45e37bdcc31) is fix the bug.
(Please check the [demo page](https://mustache.github.io/#demo) if necessary)

If it will found different behaviors as [demo page](https://mustache.github.io/#demo), I would regard as bug and fix it.
Therefore, please use the `{{{ key }}}`, If you do not want to escape in any case.

In addition, escape is specifications of the mustache. So, I am negative that it be added unescape option...

**Comment by dzimi** [comment]
Thanks, I get it. The slash char was not escaped in previous versions and it was a bug. I made an issue on rebar3 https://github.com/erlang/rebar3/issues/1264. Due to this bug in < v1.1.0, is quite risky to upgrade the bbmustache version, because path variables in form `{{ path }}` will be escaped. But it is the problem of rebar3 ...

**Comment by filmor** [comment]
Couldn't you just make this behaviour optional? Why do you need to escape slashes anyhow?

**Comment by soranoba** [comment]
@filmor 
bbmustache must conform to the specifications of the [mustache](https://mustache.github.io).

If bbmustache has the option, it will happen that someone want to escape and use the `{{key}}`, but generated text is not escape (In other words, contrary to the specification !!).
So, when I allow this, bbmustache won't be worth.

**Comment by dzimi** [comment]
I agree with @soranoba. I think that this issue can be closed and issue https://github.com/erlang/rebar3/issues/1264 should be resloved instead.

**Comment by soranoba** [comment]
That's right. I will close this issue. thanks!!

**Comment by filmor** [comment]
Wait a second, where in the spec does it say, that the forward slash is to be escaped? [Here](https://github.com/mustache/spec/blob/master/specs/interpolation.yml#L44) it actually states (as it makes sense) that only `& " < >` are to be escaped.

**Comment by soranoba** [comment]
@filmor 
Thank you for the information.
I trust [the man page](http://mustache.github.io/mustache.5.html) and [the demo page](http://mustache.github.io/#demo), and did not look at the spec.
Sorry, it is my mistake.

I will make the modification in accordance with the [spec](https://github.com/mustache/spec).
(It also included other than html escaping.)

@dzimi 
Do you is also good with this?

**Comment by dzimi** [comment]
@filmor : great job ! The demo version works with mustache.js which escapes following characters:

      var entityMap = {
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': '&quot;',
    "'": '&#39;',
    **"/": '&#x2F;'**
  };

Ruby :
 
    TABLE_FOR_ESCAPE_HTML__ = {
    "'" => '&#39;',
    '&' => '&amp;',
    '"' => '&quot;',
    '<' => '&lt;',
    '>' => '&gt;',
  }

Python:
    
    def escape(s, quote=True):
    """
    Replace special characters "&", "<" and ">" to HTML-safe sequences.
    If the optional flag quote is true (the default), the quotation mark
    characters, both double quote (") and single quote (') characters are also
    translated.
    """
    s = s.replace("&", "&amp;") # Must be done first!
    s = s.replace("<", "&lt;")
    s = s.replace(">", "&gt;")
    if quote:
        s = s.replace('"', "&quot;")
        s = s.replace('\'', "&#x27;")
    return s

As you can see , Ruby and Python does not escpae "/" , but js does. I think the strongest argument is the [spec](https://github.com/mustache/spec/blob/master/specs/interpolation.yml#L44) . So I agree with @filmor , lets straighten it out.

**Comment by soranoba** [comment]
I fix this.
Please use the v1.2.0.
https://github.com/soranoba/bbmustache/releases/tag/v1.2.0
