### ISSUE TITLE
How to render lists?

### ISSUE THREAD

**Issue by mbucc** [soranoba/bbmustache#15]
What am I doing wrong here?

```
{{#events}}
Hi {{act}}!
{{/events}}
```

```
Events = [{events, [{act, "Pink Floyd"}] }],
Parsed = bbmustache:parse_file(TemplateFileName),
bbmustache:compile(Parsed, Events).
```

The bbmustache.compile/2 returns ```<<"">>``` and I expected ```<<"Hi Pink Floyd!">>```

Thanks!

(Edit: added actual return value and what I expected.)

**Comment by soranoba** [comment]
@mbucc 

Please use the key_type option.

```erlang
>  bbmustache:render(<<"{{#events}}Hi {{act}}!{{/events}}">>, [{events, [{act, "Pink Floyd"}]}], [{key_type, atom}]).  
<<"Hi Pink Floyd!">>
```

Because, default key_type option is `string()`. So, it cannot found value, when you don't use the option.

**Comment by soranoba** [comment]
Please see [bbmustache:option/0](https://github.com/soranoba/bbmustache/blob/master/doc/bbmustache.md#type-option)

**Comment by mbucc** [comment]
Thank you, that worked.

**Comment by soranoba** [comment]
np :)
