### ISSUE TITLE
Allow disabling of html escaping

### ISSUE THREAD

**Issue by lrascao** [soranoba/bbmustache#16]
This is a rehash of #10, as i'm sure you're aware, `bbmustache` is being used in `relx` to template scripts and overlay vars, in this context we don't really need html escaping and it would be useful to disable it completely, this way users wouldn't have to use the `{{{` syntax to escape binary values in overlays variables for example.

**Comment by soranoba** [comment]
I understand these.
However, bbmustache is a mutache library. So, "{{ }}" means html escape.
This can not be changed.

If relx use 1.3.x from 1.0.x, you can be the overwrite in the following way.
**But, this method does not mean support forever**.

```erlang
1> bbmustache:render(<<"{{hoge}}">>, #{"hoge" => "<s>hoge</s>"}).         
<<"&lt;s&gt;hoge&lt;/s&gt;">>
2> bbmustache:render(<<"{{={ }=}}{{hoge}}">>, #{"hoge" => "<s>hoge</s>"}).
<<"<s>hoge</s>">>
```

**Comment by soranoba** [comment]
NOTE:
Although I am preparing the next release in the branch of the 1.3.x.
Now, this feature is not available on the branch.

**Comment by soranoba** [comment]
It will add this in v1.5.0, because equivalent function exist in [mustache.rb](https://github.com/mustache/mustache/blob/24a4cf6d293ef23db304d034b095896925921cc9/lib/mustache.rb#L192-L207).

```erlang
{escape_fun, fun((binary()) -> binary())}
```
I plan to add escape_fun to option.

**Comment by lrascao** [comment]
👍

**Comment by soranoba** [comment]
This feature was added in v1.5.0.
Please refer to https://github.com/soranoba/bbmustache/releases/tag/v1.5.0
