### ISSUE TITLE
Escaping overlay vars (mustache variables) inside template files

### ISSUE THREAD

**Issue by posilva** [soranoba/bbmustache#19]
Hi 

How to use bbmustache to allow to scape mustache variables, what I want is:
- I have a file (my_template_sys.config.tpl) that has overlay vars, for example, we always use a config like: `{environment, {{environment_var}}}.`
- When I run `rebar3 new my_template myservice` the environment config in `sys.config` is generated `{environment,  }` because in the rebar3 template generation the variable is expanded and because does not exists in the context of the rebar3 template it will be replaced by “nothing”

Any sugestion? 

Thank you

Pedro

**Comment by soranoba** [comment]
Discussion was done on slack.
https://erlanger.slack.com/archives/C055DJA49/p1493986463810192

**Comment by posilva** [comment]
Fixed using set delimiter: http://mustache.github.io/mustache.5.html

 The trick is when we want to “escape” a variable we can change the delimiter right before, and after the variable declaration we change back to the default delimiter.
```erlang

 { {{ name }}, [
        %% Application settings
        {environment, {{=<% %>=}}{{environment}}<%={{ }}=%>},
        {major, "{{=<% %>=}}{{major}}<%={{ }}=%>"},

        %% Network Settings
        {cluster_node_discover, {{=<% %>=}}{{cluster_node_discover}}<%={{ }}=%>},
        {server_interface, {{=<% %>=}}{{server_interface}}<%={{ }}=%> },
        { {{custom_parameter}}, param_value }
    ]}
```

Look that `{{custom_parameter}}` is not escaped and because the previous variables have the default delimiter after the definitions this parameter will be processed correctly by template engine.

I hope this helps
