### ISSUE TITLE
Exception on missing key

### ISSUE THREAD

**Issue by eproxus** [soranoba/bbmustache#21]
An option to crash on missing keys would be nice to have. Is this possible to implement?

**Comment by soranoba** [comment]
It can be implemented.
However, the behaviour is against the specification of mustache ([mustache is specified as complementing with empty string if key does not exist](https://github.com/mustache/spec/blob/83b0721610a4e11832e83df19c73ace3289972b9/specs/interpolation.yml#L106-L122)).

So, I'm not positive about that it will included in bbmustache.

Do you need it for debugging purposes?
For example, I think that worth considering that it will print logs when compile option enabled.

**Comment by eproxus** [comment]
The manual says:

>By default a variable "miss" returns an empty string. This can usually be configured in your Mustache library. The Ruby version of Mustache supports raising an exception in this situation, for instance.

I think it is a useful feature. We're building a dynamic set of keys from options, so it would be another manual step to double check all keys used in templates before rendering. It could also be a source of bugs in case the template is changed and someone adds a key but forgets to add a check for it.

**Comment by soranoba** [comment]
Ok, let's implement the same function as raise_on_context_miss of [mustache for ruby](https://github.com/mustache/mustache).
Wait for a few days.

-----
specifications

- It does **NOT** throw exceptions at parse.
- If raise_on_context_miss enabled, it throw exceptions on missing keys of all tags (e.g. `#`, `>`, `^`, `&`)
- However, it does **NOT** throw exceptions on skipped keys. (e.g. `{{#parent}}{{child}}{{/parent}}`, parent is false and child is not exist)

**Comment by soranoba** [comment]
This feature was added in v1.5.0.
Please refer to https://github.com/soranoba/bbmustache/releases/tag/v1.5.0

**Comment by eproxus** [comment]
Thanks a lot!
