### ISSUE TITLE
Rendering a template always accesses file on disk

### ISSUE THREAD

**Issue by hukl** [soranoba/bbmustache#32]
When rendering templates from files, I noticed that the template file is accessed each time the template is compiled. For most scenarios this is probably not mission critical but still unneccessary IO.

I used erlydtl in previous projects and remembered that they compile the templates into their own modules which export a render function. 

```my_template:render([variables])```

I liked the light weight nature of your library and so I wrote a lightweight template loader that creates modules for each template when the application is loaded.

In its current form it is probably not 100% suitable to integrate into your library and maybe you explicitly don't want such functionality.

If you are curious however, this is how I implemented it: 
https://github.com/hukl/shortcut.io_new/blob/master/src/scio_view.erl

For each .mustache file in my views folder, a corresponding module with a render function is generated in which you pass in your content. 

In my example I omitted the possibility to pass along render options or escape functions, but that could be easily added to make it more suitable for generic use in your library.

**Comment by soranoba** [comment]
Hi @hukl 

As you pointed out, bbmustache access file every time.
As a workaround, I hope that users of bbmustache will implement neccessary code yourself.

I will show you how to implement it.

- We save the template in ets like you converted it to module.
- If the same process renders multiple times, let the process keep it.
- As you did, dynamically generating modules is one way.

There are reasons not to officially support these.

- When the feature of partial is used, it is difficult to process when the referenced file changes.
- Loading a template does not necessarily use the file module. It also may load templates saved in MySQL.

For these reasons, I believe that minimizing file processing will increase the completeness as a library.

Your report is glad, and I think that this will be helpful to other users.
However, I'm sorry, bbmustache is no plans to include this feature.

**Comment by hukl** [comment]
No worries :) I just wanted to leave a not - as you said - maybe as inspiration for other users.

The partial remark is of course valid as well :) Thanks for the reply and for the library!
