### ISSUE TITLE
Adding custom serialization functions to bbmustache.

### ISSUE THREAD

**Issue by QuantamHD** [soranoba/bbmustache#33]
Hi,

Our team currently has a need to offer users the ability to output maps as types for mustache serialization. I was wondering if I could add custom serializers to the library so that the user could select specific serialization functions for types not supported currently?

Current Behaviour

```elixir
:bbmustache.render("{{test}}", %{"test" => %{"weee" => 2}}, key_type: :binary)
** (ArgumentError) argument error
    :erlang.iolist_to_binary(%{"weee" => 2})
    (bbmustache) /Users/ethan/new_faspex4/f4-dev-setup/microservices/workflow-engine/deps/bbmustache/src/bbmustache.erl:233: :bbmustache.compile_impl/4
    (bbmustache) /Users/ethan/new_faspex4/f4-dev-setup/microservices/workflow-engine/deps/bbmustache/src/bbmustache.erl:218: :bbmustache.compile/3
```

Proposed Behaviour

```elixir
iex(1)> :bbmustache.render("{{test}}", %{"test" => %{"weee" => 2}}, key_type: :binary, map_serializer: fn x -> JSON.encode!() end)
"{\"weee\":2}"
```

**Comment by soranoba** [comment]
Hi @QuantamHD 

It is not currently supported.
I thought that behaviour was great, so I will add it on weekends.

NOTE-1:
Notice that if you use two mustaches (`{{  }}`), it will escape after serialization.
If you do not want it, please use three mustaches (`{{{  }}}`).

NOTE-2:
The serialization feature will be not limited to maps.
I am considering that it delegate serialization for all terms and provide a default serializer.

**Comment by QuantamHD** [comment]
Oh hey I just made a PR for the feature.

**Comment by soranoba** [comment]
Great.

**Comment by QuantamHD** [comment]
Need some help on adding tests for it thought a bit weak on Erlang. haha

**Comment by soranoba** [comment]
resolved.
