### ISSUE TITLE
Use a fun as Data

### ISSUE THREAD

**Issue by k32** [soranoba/bbmustache#36]
Currently one can supply a proplist or a map as `Data` argument to `render` function. However it may be useful to use a custom function as well. This should be very easy to implement: just add a `when is_function` clause to `find_data/2`... 

I can create a PR unless anyone got objections.

**Comment by soranoba** [comment]
Hm ...

The PR probably works properly, but I do not feel that need.
In labmda, it would be easier to use simplified data.

So why does it support `assoc list`?
The project I was working on when I created `bbmustache` was not able to use maps.
Then time has passed.
I will stop to support `assoc list` when incrementing major version.

Please fork and remodel `bbmustache` to use it easy for yourself.

Thanks.

**Comment by k32** [comment]
Well my idea was that using a closure as `data` in theory allows to use _any_ key-value storage without modifying bbmustache.erl... It will allow storing data in dict, ets, map and what not. So it's just "the" generic solution. In theory it would allow to remove lots of map-related `ifdef`s from the code to make it nicer. 
That's why I think it's worth integrating into the upstream. But anyways, it's your decision to make.

**Comment by Vagabond** [comment]
You could also do things like have `key.base64` in case you wanted (or `base64(key)`) in the template, to turn something into base64 and parse that out in your data fun before doing the lookup.

I'm looking at doing some more sophisticated templating with bbmustache and I would like to have this option as well.

**Comment by soranoba** [comment]
https://github.com/soranoba/bbmustache/pull/53#issuecomment-751933393
