### ISSUE TITLE
Wrong parsing when closing tag is on separate line

### ISSUE THREAD

**Issue by ileamo** [soranoba/bbmustache#42]
When rendering template I get unexpected result:
```
iex(7)> :bbmustache.render "{{#foo}}bar\n{{/foo}}    \n", [{'foo', fn x, _ -> "<#{x}>" end}]
"<bar\n{{/fo>"
```
Function receives argument with extra chars.
Must be `<bar\n>`, got `<bar\n{{/fo>`.
It seems to be a wrong parsing when closing tag is on a separate line:
```
iex(8)> :bbmustache.parse_binary "{{#foo}}bar\n{{/foo}}    \n"
{:bbmustache, [{:"#", ["foo"], ["bar\n"], "bar\n{{/fo"}], [], [], [], []}
```

**Comment by soranoba** [comment]
Thank you for the report.
I already have fixed it, and I will release it within a few days.

**Comment by ileamo** [comment]
Thanks.
