### ISSUE TITLE
Problems loading partials on Elixir project

### ISSUE THREAD

**Issue by DaniFrancisco** [soranoba/bbmustache#55]
Hey,

I'm working on an elixir project and I'm having some problems to make partials to work. I've the partials in a local file, same place as the templates. 

_/templates/my_template.mustache_
```
{{> partial}}
```

_/templates/partial.mustache_
```
<h1>Hey there</h1>
```

I keep getting an empty string when I render the `my_template`. Should it work out of the box like this or am I missing something 😅 ? Is there any examples I could look into?

Thanks!

**Comment by soranoba** [comment]
This is an execution example using partial.
https://github.com/soranoba/bbmustache/blob/93b307692bb0ba745143f4db4cccd6d9fb420ea9/ct/bbmustache_SUITE.erl#L131-L136




Do you call `bbmustache:parse_file/1` or `bbmustache:parse_file/2`?
If you use `bbmustache:parse_binary/1` or `bbmustache:parse_binary/2`, bbmustache can't figure out the directory correctly.

**Comment by DaniFrancisco** [comment]
Yup! That did the trick! 🥇 

Thank you so much @soranoba, this is going to make my life a lot easier 😄 

Closing this.
