### ISSUE TITLE
Unicode support in value fetching.

### ISSUE THREAD

**Issue by ferd** [soranoba/bbmustache#61]
See https://github.com/erlang/rebar3/issues/2644

The issue is located within https://github.com/soranoba/bbmustache, specifically at https://github.com/soranoba/bbmustache/blob/7631da97b0c4de54753257e126cb6f983d0c4b83/src/bbmustache.erl#L278, where the code should likely call for `unicode:characters_to_binary` instead of `iolist_to_binary`.

There are likely other locations for such calls, but sending in unicode data that has a wide representation can break when the codepoints get too large with the current calls.

**Comment by soranoba** [comment]
I'm checking the correction within the scope of the test.
If you need to take other measures, please create a new issue.

Thanks for the report
