### ISSUE TITLE
Anyway to skip over unclosed tags?

### ISSUE THREAD

**Issue by jsmestad** [soranoba/bbmustache#69]
## Scenario

I have a LiveView text area that supports mustache templates to be entered on each keystroke, I call `:bbmustache.render(text, %{"time" => DateTime.utc_now()}, key_type: :binary)`. As the user is typing their input like this `It is currently {` then they hit one more `{` (`It currently {{`) the bbmustache will blow up with an `unclosed_tags` error.

Is there a way to have bbmustache just ignore unclosed tags and render them as `{{` until a closed tag is detected?

**Comment by soranoba** [comment]
There is no way.
I think it's easy to write a patch that only handles trailing start tags, but it's hard to render when users add start tags in the middle.
