### ISSUE TITLE
Wrong Version in .app file

### ISSUE THREAD

**Issue by tsloughter** [soranoba/bbmustache#9]
The package in hex.pm doesn't work properly with rebar3 because the version in the `.app.src` is set to `git`. This means rebar3 will always think it has the wrong version of bbmustache and continually try to upgrade when building a project.

If you use `rebar3 hex cut` you can easily set the new version in `.app.src` and publish https://asciinema.org/a/32q4wprb5crr3zpvldlv4f4bs

**Comment by soranoba** [comment]
Oops, sorry. I repaired it.
https://github.com/soranoba/bbmustache/commit/6fcf531359e25eb90886580df3ac081adad3ec3c

Asciinema became very helpful. Thanks !

**Comment by tsloughter** [comment]
Awesome, works! Thanks

One last thing :), I'd suggest putting `{plugins, [rebar3_hex]}.` in `~/.config/rebar3/rebar.config`, only put plugins that are necessary for building the app in the default profile of the apps rebar config. Otherwise anyone using `bbmustache` will also get the `rebar3_hex` plugin in their project even though they don't need it.

**Comment by soranoba** [comment]
Ok. I modified this.
https://github.com/soranoba/bbmustache/commit/8cafa7bf03802a85312c7112364f4c68deab22df

I was learn a lot thing at issues. Thanks =D

**Comment by tsloughter** [comment]
Thanks!
